/*
TASK - Data Manipulation Exercises
Backend - ASP.NET Core
Database: CompanyDB
Schema: Sales
SQL Server
*/

-- =========================================================
-- PART 1: DATABASE, SCHEMA, EMPLOYEES TABLE
-- =========================================================

CREATE DATABASE CompanyDB;
GO

USE CompanyDB;
GO

CREATE SCHEMA Sales;
GO

-- Sequence instead of IDENTITY
CREATE SEQUENCE Sales.EmployeeIdSequence
    AS INT
    START WITH 1
    INCREMENT BY 1;
GO

CREATE TABLE Sales.employees
(
    employee_id INT NOT NULL
        CONSTRAINT PK_employees PRIMARY KEY
        DEFAULT (NEXT VALUE FOR Sales.EmployeeIdSequence),
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    salary DECIMAL(10,2)
);
GO

ALTER TABLE Sales.employees
ADD hire_date DATE;
GO

/*
Mockaroo-style mock data.
The employee_id values are generated by the sequence.
*/
INSERT INTO Sales.employees (first_name, last_name, salary, hire_date)
VALUES
('John', 'Smith', 52000.00, '2020-01-15'),
('Jane', 'Johnson', 61000.00, '2020-06-20'),
('Michael', 'Williams', 48000.00, '2019-11-10'),
('Sarah', 'Brown', 57000.00, '2021-03-12'),
('David', 'Jones', 43000.00, '2022-02-18'),
('Emily', 'Davis', 68000.00, '2023-07-01'),
('Daniel', 'Wilson', 55000.00, '2020-09-25'),
('Olivia', 'Taylor', 45000.00, '2021-12-05'),
('James', 'Anderson', 59000.00, '2022-05-16'),
('Sophia', 'Thomas', 51000.00, '2020-04-08'),
('Robert', 'Moore', 39000.00, NULL),
('Emma', 'Martin', 62000.00, '2023-01-10'),
('William', 'Jackson', 47000.00, '2021-08-22'),
('Ava', 'Thompson', 73000.00, '2022-11-30'),
('Joseph', 'White', 50000.00, '2020-12-14'),
('Mia', 'Harris', 46000.00, '2023-03-09'),
('Charles', 'Sanchez', 64000.00, '2021-05-27'),
('Isabella', 'Clark', 58000.00, '2022-01-19'),
('Thomas', 'Lewis', 41000.00, '2024-02-11'),
('Amelia', 'Robinson', 66000.00, '2020-10-03');
GO

-- =========================================================
-- DATA MANIPULATION EXERCISES
-- =========================================================

-- 1. Select all columns
SELECT *
FROM Sales.employees;
GO

-- 2. Retrieve only first_name and last_name
SELECT first_name, last_name
FROM Sales.employees;
GO

-- 3. Retrieve full name as one column
SELECT CONCAT(first_name, ' ', last_name) AS [full name]
FROM Sales.employees;
GO

-- 4. Show average salary
SELECT AVG(salary) AS AverageSalary
FROM Sales.employees;
GO

-- 5. Salary greater than 50000
SELECT *
FROM Sales.employees
WHERE salary > 50000;
GO

-- 6. Employees hired in 2020
SELECT *
FROM Sales.employees
WHERE YEAR(hire_date) = 2020;
GO

-- 7. Last names start with S
SELECT *
FROM Sales.employees
WHERE last_name LIKE 'S%';
GO

-- 8. Top 10 highest-paid employees
SELECT TOP 10 *
FROM Sales.employees
ORDER BY salary DESC;
GO

-- 9. Salaries between 40000 and 60000
SELECT *
FROM Sales.employees
WHERE salary BETWEEN 40000 AND 60000;
GO

-- 10. Names containing 'man'
SELECT *
FROM Sales.employees
WHERE CONCAT(first_name, ' ', last_name) LIKE '%man%';
GO

-- 11. NULL hire_date
SELECT *
FROM Sales.employees
WHERE hire_date IS NULL;
GO

-- 12. Salary in (40000, 45000, 50000)
SELECT *
FROM Sales.employees
WHERE salary IN (40000, 45000, 50000);
GO

-- 13. Hired between 2020-01-01 and 2021-01-01
SELECT *
FROM Sales.employees
WHERE hire_date BETWEEN '2020-01-01' AND '2021-01-01';
GO

-- 14. Salaries descending
SELECT *
FROM Sales.employees
ORDER BY salary DESC;
GO

-- =========================================================
-- ADDITIONAL DATA MANIPULATION EXERCISES
-- =========================================================

-- 15. First 5 employees ordered by last_name ascending
SELECT TOP 5 *
FROM Sales.employees
ORDER BY last_name ASC;
GO

-- 16. Salary > 55000 and hired in 2020
SELECT *
FROM Sales.employees
WHERE salary > 55000
  AND YEAR(hire_date) = 2020;
GO

-- 17. First name is John or Jane
SELECT *
FROM Sales.employees
WHERE first_name IN ('John', 'Jane');
GO

-- 18. Salary <= 55000 and hire date after 2022-01-01
SELECT *
FROM Sales.employees
WHERE salary <= 55000
  AND hire_date > '2022-01-01';
GO

-- 19. Salary greater than average salary
SELECT *
FROM Sales.employees
WHERE salary > (SELECT AVG(salary) FROM Sales.employees);
GO

-- 20. 3rd to 7th highest-paid employees
SELECT *
FROM Sales.employees
ORDER BY salary DESC
OFFSET 2 ROWS
FETCH NEXT 5 ROWS ONLY;
GO

-- 21. Hired after 2021-01-01 in alphabetical order
SELECT *
FROM Sales.employees
WHERE hire_date > '2021-01-01'
ORDER BY last_name ASC, first_name ASC;
GO

-- 22. Salary > 50000 and last name not starting with A
SELECT *
FROM Sales.employees
WHERE salary > 50000
  AND last_name NOT LIKE 'A%';
GO

-- 23. Salary is not NULL
SELECT *
FROM Sales.employees
WHERE salary IS NOT NULL;
GO

-- 24. Names containing 'e' or 'i' and salary > 45000
SELECT *
FROM Sales.employees
WHERE (CONCAT(first_name, ' ', last_name) LIKE '%e%'
    OR CONCAT(first_name, ' ', last_name) LIKE '%i%')
  AND salary > 45000;
GO

-- =========================================================
-- JOIN-RELATED EXERCISES
-- =========================================================

-- Create departments table
CREATE TABLE Sales.departments
(
    department_id INT NOT NULL
        CONSTRAINT PK_departments PRIMARY KEY,
    department_name VARCHAR(100),
    manager_id INT NULL
        CONSTRAINT FK_departments_manager
        REFERENCES Sales.employees(employee_id)
);
GO

-- Add department_id to employees
ALTER TABLE Sales.employees
ADD department_id INT NULL;
GO

-- Create foreign key from employees to departments
ALTER TABLE Sales.employees
ADD CONSTRAINT FK_employees_department
FOREIGN KEY (department_id)
REFERENCES Sales.departments(department_id);
GO

-- Insert departments
INSERT INTO Sales.departments (department_id, department_name, manager_id)
VALUES
(1, 'IT', 2),
(2, 'HR', 4),
(3, 'Sales', 6),
(4, 'Finance', 9),
(5, 'Marketing', 14);
GO

-- Assign employees to departments
UPDATE Sales.employees SET department_id = 1 WHERE employee_id IN (1, 2, 3, 4);
UPDATE Sales.employees SET department_id = 2 WHERE employee_id IN (5, 6, 7, 8);
UPDATE Sales.employees SET department_id = 3 WHERE employee_id IN (9, 10, 11, 12);
UPDATE Sales.employees SET department_id = 4 WHERE employee_id IN (13, 14, 15, 16);
UPDATE Sales.employees SET department_id = 5 WHERE employee_id IN (17, 18, 19);
-- Employee 20 is intentionally left without a department.
GO

-- 25. All employees with department names (INNER JOIN)
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    e.salary,
    e.hire_date,
    d.department_name
FROM Sales.employees AS e
INNER JOIN Sales.departments AS d
    ON e.department_id = d.department_id;
GO

-- 26. Employees who don't belong to any department
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    e.salary
FROM Sales.employees AS e
LEFT JOIN Sales.departments AS d
    ON e.department_id = d.department_id
WHERE d.department_id IS NULL;
GO

-- 27. All departments and employee count
SELECT
    d.department_id,
    d.department_name,
    COUNT(e.employee_id) AS employee_count
FROM Sales.departments AS d
LEFT JOIN Sales.employees AS e
    ON d.department_id = e.department_id
GROUP BY d.department_id, d.department_name;
GO

-- 28. Highest-paid employee in each department
SELECT
    d.department_id,
    d.department_name,
    MAX(e.salary) AS HighestSalary
FROM Sales.departments AS d
INNER JOIN Sales.employees AS e
    ON d.department_id = e.department_id
GROUP BY d.department_id, d.department_name;
GO

-- =========================================================
-- PART 1: STORED PROCEDURES
-- =========================================================

CREATE TABLE Employees
(
    Id INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Salary DECIMAL(10,2)
);
GO

-- 1. GetAllEmployees
CREATE PROCEDURE GetAllEmployees
AS
BEGIN
    SELECT *
    FROM Employees;
END;
GO

-- 2. GetHighSalaryEmployees
CREATE PROCEDURE GetHighSalaryEmployees
    @MinSalary DECIMAL(10,2)
AS
BEGIN
    SELECT *
    FROM Employees
    WHERE Salary > @MinSalary;
END;
GO

-- 3. AddEmployee
CREATE PROCEDURE AddEmployee
    @FirstName VARCHAR(50),
    @LastName VARCHAR(50),
    @Salary DECIMAL(10,2)
AS
BEGIN
    INSERT INTO Employees (Id, FirstName, LastName, Salary)
    VALUES
    (
        ISNULL((SELECT MAX(Id) + 1 FROM Employees), 1),
        @FirstName,
        @LastName,
        @Salary
    );
END;
GO

-- =========================================================
-- PART 2: EMPLOYEE LOG + AFTER INSERT TRIGGER
-- =========================================================

CREATE TABLE EmployeeLog
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    EmployeeId INT,
    Action VARCHAR(50),
    ActionDate DATETIME
);
GO

CREATE TRIGGER trg_AfterInsertEmployee
ON Employees
AFTER INSERT
AS
BEGIN
    INSERT INTO EmployeeLog (EmployeeId, Action, ActionDate)
    SELECT
        Id,
        'INSERT',
        GETDATE()
    FROM inserted;
END;
GO

-- =========================================================
-- OPTIONAL TESTS FOR STORED PROCEDURES AND TRIGGER
-- =========================================================

EXEC AddEmployee
    @FirstName = 'Adam',
    @LastName = 'Scott',
    @Salary = 60000;
GO

EXEC GetAllEmployees;
GO

EXEC GetHighSalaryEmployees
    @MinSalary = 50000;
GO

SELECT *
FROM EmployeeLog;
GO

-- =========================================================
-- SEARCH TASK
-- =========================================================

/*
1. DELETE vs TRUNCATE

DELETE:
- Removes rows from a table.
- Can use a WHERE condition.
- Is logged row by row.
- DELETE can be used when specific rows need to be removed.
- The table structure remains.

TRUNCATE:
- Removes all rows from a table.
- Does not support a WHERE clause.
- Uses fewer log resources than DELETE in normal cases.
- Resets an IDENTITY counter in SQL Server.
- The table structure remains.

Example:
DELETE FROM Employees WHERE Id = 1;
TRUNCATE TABLE Employees;
*/

/*
2. TRANSACTION LOG BACKUP

A Transaction Log Backup is a backup of the database transaction log.
It records database changes so the transaction log can be backed up
and, with an appropriate recovery model, can support point-in-time
recovery.

Example:
BACKUP LOG CompanyDB
TO DISK = 'C:\Backup\CompanyDB_Log.trn';
*/

/*
3. WHAT IS A DATABASE JOB?

A database job is a scheduled task that automatically performs
database-related operations at a specified time or on a specified
schedule.

In SQL Server, jobs are commonly created and managed using SQL Server
Agent. Examples include backups, maintenance, data cleanup, and
scheduled stored procedure execution.
*/
